Add pagination to jobs applied by student
CS178A-B/final-project-jmsv pull request #64
Opened 2021-02-08 22:55 UTC by Mari-Hayashi

2021-02-08 23:53 UTC, johan1505 requested changes
Minor change

2021-02-08 23:53 UTC, johan1505 commented on src/client/src/Domains/Jobs/api/index.ts
>      return API.get<{ jobApplications: IJobApplication[] }>(
add `jobApplicationsCount: number`

2021-02-09 18:02 UTC, Mari-Hayashi commented on src/client/src/Domains/Jobs/api/index.ts
>      return API.get<{ jobApplications: IJobApplication[] }>(
Done.

2021-02-09 19:38 UTC, johan1505 approved these changes

2021-02-09 19:38 UTC, merged