Improve student search.
CS178A-B/final-project-jmsv pull request #88
Opened 2021-02-23 22:54 UTC by Mari-Hayashi

Improved the student search so that students whose profile matches perfectly with the specified query appear first in the search result.

![studentSearch](https://user-images.githubusercontent.com/43657669/108918816-d320c480-75e6-11eb-8466-6d9eb87f7005.gif)

*For example, when I specify "Computer Science" as a department, the CS majors appear top of students with major "not specified".

2021-02-25 01:40 UTC, johan1505 requested changes

2021-02-25 01:40 UTC, johan1505 commented on src/server/src/modules/student.ts
> +    const filteredPartialMatchStudents = partialMatchStudents.filter(function (student) {
Minor style improvement

`const filteredPartialMatchStudents = partialMatchStudents.filter((student) => perfectMatchStudentIds.indexOf(student.id) === -1))`

2021-02-26 00:34 UTC, Mari-Hayashi commented on src/server/src/modules/student.ts
> +    const filteredPartialMatchStudents = partialMatchStudents.filter(function (student) {
Done.

2021-02-26 22:12 UTC, johan1505 approved these changes

2021-02-26 22:12 UTC, merged